### ISSUE TITLE
NotImplementedError: 

### ISSUE THREAD

**Issue by fvegamaza** [JuanPabloMF/deep-learning-platzi#4]
Just before trining the net me and a couple of students had this error:
`for epoch in range(num_epochs):
  print('Epoch {}/{}'.format(epoch+1, num_epochs))
  print('-'*10)
  
  running_loss = RunningMetric() # perdida
  running_acc = RunningMetric() #precision
  
  for inputs, targets in dataloader:
    inputs, targets = inputs.to(device), targets.to(device)
    optimizer.zero_grad()

    outputs = net(inputs)
    _, preds = torch.max(outputs,1)
    loss = loss_fn(outputs, targets)
    
    loss.backward() #magias: gradientes calculados automaticamente
    optimizer.step() #magia2: actualiza las perillas o los parametros
    
    batch_size = inputs.size()[0]
    running_loss.update(loss.item()*batch_size,
                       batch_size)
    running_acc.update(torch.sum(preds == targets).float(),
                       batch_size)
  print("Loss: {:.4f} Acc: {:.4f} ".format(running_loss(),
                                          running_acc()))`

Output:
`Epoch 1/100
----------
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-103-a31d19800cba> in <module>()
     10     optimizer.zero_grad()
     11 
---> 12     outputs = net(inputs)
     13     _, preds = torch.max(outputs,1)
     14     loss = loss_fn(outputs, targets)

1 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _forward_unimplemented(self, *input)
    199         registered hooks while the latter silently ignores them.
    200     """
--> 201     raise NotImplementedError
    202 
    203 

NotImplementedError: `

I tried simple things to fix it, like restarting and re-install some packages but without any good results

**Comment by JuanPabloMF** [comment]
Hi Franco,

Can you please share the google colab you are using so I can take a good look at the code, and eventually run the cell to try and debug? If not possible please share the code you are running (I can see some of it in the traceback, but it's best to have all the info).

**Comment by fvegamaza** [comment]
Sure!
https://colab.research.google.com/drive/1QBlbLtdJA3YnLHaMo31o6oCx-Rdl-Kkt?usp=sharing

Last night I tried downgrade torch package and torchvision as well

**Comment by margori** [comment]
@fvegamaza I had same issue.

Solved by changing the indentation of function `forward` in class `net`
```
class Net(nn.Module):
  def __init__(self, num_channels):
    ...
  
  def forward(self,x):
    #Empieza 3x64x64
    ...
    return x
  ```

**Comment by fvegamaza** [comment]
Thanks for your reply! I really appreciate it. You should do the pull request to fix it. Until now, Platzi has not be able to find a solution, despite I sent them several emails explained it.

**Comment by JuanPabloMF** [comment]
@margori it would be lovely if you could do a pull request so I can add the fix to the code base. Else I'll add this as soon as I get some free time from my work.
